version: "3.9"
services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongoVolume:/data/db
  app:
    container_name: traffic-detector
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongo/detector
      - SPRING_DATA_MONGODB_HOST=mongo
